export const AuthActionsTypes = {
  REGISTER_START: 'REGISTER_START',
  REGISTER_SUCESS: 'REGISTER_SUCESS',
  REGISTER_ERROR: 'REGISTER_ERROR',

  LOGIN_START: 'LOGIN_START',
  LOGIN_SUCESS: 'LOGIN_SUCESS',
  LOGIN_ERROR: 'LOGIN_ERROR',
};
